[package]
name = "mirust"
version = "1.2.0"
edition = "2024"
rust-version = "1.85"
license = "MIT"
description = "Write mIRC and AdiIRC DLLs in safe, idiomatic Rust."
homepage = "https://github.com/irc-rs/mirust"
repository = "https://github.com/irc-rs/mirust"
documentation = "https://docs.rs/mirust"
readme = "README.md"
keywords = ["irc", "mirc", "adiirc", "dll", "ffi"]
categories = ["api-bindings", "development-tools::ffi", "os::windows-apis"]
exclude = ["/.github", "/mirc_docs", "/MATRIX.md"]

[dependencies]

[package.metadata.docs.rs]
default-target = "i686-pc-windows-msvc"
targets = ["i686-pc-windows-msvc", "x86_64-pc-windows-msvc", "aarch64-pc-windows-msvc"]

[[example]]
name = "hello"
crate-type = ["cdylib"]
